wandb_version: 1

seed:
  desc: null
  value: 42
model:
  desc: null
  value: rnn
dataset:
  desc: null
  value: /mydata/deepcloud/salman/dataset/h5_data_all_chuncked
save:
  desc: null
  value: /mydata/deepcloud/yves/A_RadiativeFlux/results/rnn_medium
percent:
  desc: null
  value: 0.1
subsample:
  desc: null
  value: 0.1
num_workers:
  desc: null
  value: 4
prefetch_factor:
  desc: null
  value: 2
wandb_mode:
  desc: null
  value: online
num_cells:
  desc: null
  value: 81920
train:
  desc: null
  value: false
test:
  desc: null
  value: true
shuffle:
  desc: null
  value: true
batch_size:
  desc: null
  value: 512
optimizer:
  desc: null
  value: adamw
clip:
  desc: null
  value: 1.0
num_epoch:
  desc: null
  value: 80
learning_rate:
  desc: null
  value: 0.0005
hidden_dim:
  desc: null
  value: 256
layers:
  desc: null
  value: 4
dropout:
  desc: null
  value: 0.0
channel_out:
  desc: null
  value: 4
channel_3d:
  desc: null
  value: 6
channel_2d:
  desc: null
  value: 6
patch_size:
  desc: null
  value: 2
scale_output:
  desc: null
  value: true
height_in:
  desc: null
  value: 70
heads:
  desc: null
  value: 6
dim_head:
  desc: null
  value: 64
emb_dropout:
  desc: null
  value: 0.0
afno_sparsity_threshold:
  desc: null
  value: 0.01
hard_thresholding_fraction:
  desc: null
  value: 1
cutoff_frequency:
  desc: null
  value: 0.1
zero_freq_indices:
  desc: null
  value: null
fno_blocks:
  desc: null
  value: 8
hidden_size_factor:
  desc: null
  value: 1
double_skip:
  desc: null
  value: true
mlp_ratio:
  desc: null
  value: 4.0
max_skip:
  desc: null
  value: 3
fully_connected:
  desc: null
  value: false
edge_channels_in:
  desc: null
  value: 1
heights_file:
  desc: null
  value: null
lstm_units:
  desc: null
  value:
  - 64
  - 64
  - 128
  - 128
  - 256
  - 256
mlp_units:
  desc: null
  value:
  - 64
  - 128
lstm_droprate:
  desc: null
  value: 0.0
_wandb:
  desc: null
  value:
    code_path: code/train_models.py
    python_version: 3.9.15
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1745434382
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 1
      - 5
      - 13
      - 14
      - 15
      - 16
      - 23
      - 35
      - 62
      4: 3.9.15
      5: 0.17.0
      8:
      - 5
      13: linux-x86_64
timing_runs:
  desc: null
  value: 1
