wandb_version: 1

seed:
  desc: null
  value: 42
model:
  desc: null
  value: gnn_graphCast_column
dataset:
  desc: null
  value: /mydata/deepcloud/salman/dataset/h5_data_all_chuncked
save:
  desc: null
  value: /mydata/deepcloud/yves/results_git/gnn_graphCast_Emb128
percent:
  desc: null
  value: 0.1
subsample:
  desc: null
  value: 0.1
num_workers:
  desc: null
  value: 4
prefetch_factor:
  desc: null
  value: 2
wandb_mode:
  desc: null
  value: online
num_cells:
  desc: null
  value: 81920
train:
  desc: null
  value: true
test:
  desc: null
  value: true
shuffle:
  desc: null
  value: true
batch_size:
  desc: null
  value: 2048
vbatch:
  desc: null
  value: 1
optimizer:
  desc: null
  value: adamw
clip:
  desc: null
  value: 1.0
num_epoch:
  desc: null
  value: 100
learning_rate:
  desc: null
  value: 0.0005
patch_size:
  desc: null
  value: 1
hidden_dim:
  desc: null
  value: 128
layers:
  desc: null
  value: 16
vit_heads:
  desc: null
  value: 6
vit_dropout:
  desc: null
  value: 0.0
afno_sparsity_threshold:
  desc: null
  value: 0.01
hard_thresholding_fraction:
  desc: null
  value: 1
cutoff_frequency:
  desc: null
  value: 0.1
zero_freq_indices:
  desc: null
  value: null
gaussian_params_file_LWDown:
  desc: null
  value: null
gaussian_params_file_LWUp:
  desc: null
  value: null
heads:
  desc: null
  value: 4
use_scheduler:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    code_path: code/train_column.py
    python_version: 3.9.15
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1739811955
    t:
      1:
      - 1
      - 55
      - 77
      3:
      - 13
      - 14
      - 15
      - 16
      - 23
      - 35
      4: 3.9.15
      5: 0.17.0
      8:
      - 5
      13: linux-x86_64
